### ISSUE TITLE
Use python logging instead of print()

### ISSUE THREAD

**Issue by elupus** [XKNX/xknx#46] opened 2017-07-30 21:05 UTC
The library should use python logging instead of print so that logging ends up correct format in using applications like home assistant.

**Comment by Julius2342** [comment] 2017-07-30 21:07
Yes :-) will add this as the next thing. It is also a duplicate of #26

**Comment by elupus** [comment] 2017-07-30 21:15
Whoops.. Sorry. My initial hass tests look good. Way more performant. Especially when you have sensors that don't reply as expected.

**Comment by Julius2342** [comment] 2017-07-30 21:19
If you have any ideas for improvement, tell me.

**Comment by resoai** [comment] 2017-07-31 13:10
HVAC support for XKNX Climate, please! This along with setpoint shifts will bring hass to the next level!

**Comment by Julius2342** [comment] 2017-07-31 13:51
@resoai : may you open a separate ticket for HVAC? I'm happy to implement this, but i need your help, bc i live in a country were AC is not needed :-)

My general plan is to add support for RTR (Room Temperature Regulation). The next step is to add valve support for my heating system. Would it be something similar for AC?

**Comment by resoai** [comment] 2017-07-31 13:55
To be honest I don't have A/C myself (same issue) but we do have heated floors which are being controlled via KNX. I'll be more than happy to test it and give you as much support as i can. Let's wait till PR is approved and merged and I'll start testing XKNX and shall create a separate ticket for HVAC :) I will be able to test HVAC with A/C on a remote house though!

**Comment by elupus** [comment] 2017-08-03 19:31
Think you can close this issue. Logging is using python logging now.

**Comment by Julius2342** [comment] 2017-08-03 19:41
Doing so!

**Closed by Julius2342** 2017-08-03 19:41 UTC
